language: python

python:
  - "2.7"
  - "3.2"
  - "3.4"

env:
  - PYTHONPATH=$PYTHONPATH:$PWD DJANGO_VERSION=1.8
  - PYTHONPATH=$PYTHONPATH:$PWD DJANGO_VERSION=1.9
  - PYTHONPATH=$PYTHONPATH:$PWD DJANGO_VERSION=1.10

matrix:
  exclude:
   - python: "3.2"
     env: PYTHONPATH=$PYTHONPATH:$PWD DJANGO_VERSION=1.9
   - python: "3.2"
     env: PYTHONPATH=$PYTHONPATH:$PWD DJANGO_VERSION=1.10

install:
  - pip install Django==$DJANGO_VERSION pytest pytest-django

script:
  - pytest
