# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('speed', models.BooleanField(default=False, verbose_name='track speed')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'analytics code',
                'verbose_name_plural': 'analytics codes',
                'ordering': ('site', 'code'),
            },
        ),
        migrations.CreateModel(
            name='SiteVerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'site verification code',
                'verbose_name_plural': 'site verification codes',
                'ordering': ('site', 'code'),
            },
        ),
    ]
